version: '3.3'

networks:
  smart4all-net:
    external: true
  
services:
  
  ## Reverse Proxy
  traefik:
    image: traefik:v2.9
    container_name: traefik
    networks:
      - smart4all-net
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configurations/traefik.yml:/etc/traefik/traefik.yml:ro"
    ports:
      - "80:80"
      - "8080:8080"
  
  ## MQTT Broker
  mqtt-broker:
    image: emqx/emqx:5.6.1
    container_name: mqtt-broker
    restart: unless-stopped
    networks:
      - smart4all-net
    environment:
      - EMQX_ADMIN_PASSWORD=brokerpw
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_web_hook"
    ports:
      - "18083:18083"
      - "1883:1883"
  
  ## Data Streams DB
  streams-db:
    image: bitnami/cassandra:4.0
    container_name: streams-db
    networks:
      - smart4all-net
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME="smart4all-cluster"
    volumes:
    - "./configurations/cassandra:/docker-entrypoint-initdb.d"
    ports:
      - "9042:9042"
  
  ## PostgreSQL Database
  localization-db:
    image: postgres:13.1-alpine
    container_name: localization-db
    networks:
      - smart4all-net
    restart: unless-stopped
    environment:
      # Credentials root/defaultpass
      - POSTGRES_PASSWORD=defaultpass
      - POSTGRES_DB=iot
    ports:
      - "5432:5432"

  ## Devices Manager
  devices-manager:
    build:
      context: ./applications/devices-manager
    container_name: devices-manager
    networks:
      - smart4all-net
    restart: unless-stopped
    depends_on:
      - localization-db
      - mqtt-broker
    volumes:
      - "./applications/devices-manager/application.properties:/app/config/application.properties:ro"
  
  ## Localization Processor
  rssi-processor:
    build:
      context: ./applications/rssi-processor
    container_name: rssi-processor
    networks:
      - smart4all-net
    depends_on:
      - mqtt-broker
      - streams-db
      - devices-manager
    restart: unless-stopped
    volumes:
      - "./applications/rssi-processor/application.properties:/app/config/application.properties:ro"