version: '3.3'

networks:
  esda-net:
    external: true
  
services:
  
  ## Reverse Proxy
  traefik:
    image: traefik:v2.9 ## TODO Get latest version
    container_name: traefik
    networks:
      - esda-net
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configurations/traefik.yml:/etc/traefik/traefik.yml:ro"
    ports:
      - "80:80"
      - "8080:8080"
  
  ## MQTT Broker
  mqtt-broker:
    image: emqx/emqx:5.1.3  ## TODO Get latest version
    container_name: mqtt-broker
    restart: unless-stopped
    networks:
      - esda-net
    environment:
      - EMQX_ADMIN_PASSWORD=brokerpw
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_web_hook"
    ports:
      - "18083:18083"
      - "1883:1883"