## Static Configuration
log:
  level: INFO

api:
  insecure: true
  dashboard: true

ping: {}

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false